#!/usr/bin/env python3
"""
Regenerates the product cards in index.html from the "Poke Liberty Product
Inventory" Google Sheet + "Poke Liberty Product Images" Drive folder.

Run automatically by .github/workflows/sync-inventory.yml on a schedule, or
manually:

    export GOOGLE_SERVICE_ACCOUNT_KEY="$(cat service-account.json)"
    export SHEET_ID=...
    export DRIVE_FOLDER_ID=...
    python3 scripts/build_products.py

Sheet columns expected (header row): id, category, name, description, price,
stock, image_filename, payment_link, active
"""
import html
import io
import json
import os
import sys
from pathlib import Path

from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_HTML = REPO_ROOT / "index.html"
IMAGES_DIR = REPO_ROOT / "images"

BEGIN_MARKER = "<!-- BEGIN PRODUCTS: generated by scripts/build_products.py — do not hand-edit between these markers -->"
END_MARKER = "<!-- END PRODUCTS -->"

# Categories render in this order; anything else found in the sheet is
# appended alphabetically after these.
CATEGORY_ORDER = ["Sealed Product", "Singles for Collection", "Raw Cards for Grading"]

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets.readonly",
    "https://www.googleapis.com/auth/drive.readonly",
]


def get_credentials():
    key_json = os.environ["GOOGLE_SERVICE_ACCOUNT_KEY"]
    info = json.loads(key_json)
    return service_account.Credentials.from_service_account_info(info, scopes=SCOPES)


def fetch_rows(sheets_service, sheet_id):
    result = sheets_service.spreadsheets().values().get(
        spreadsheetId=sheet_id, range="A:Z"
    ).execute()
    values = result.get("values", [])
    if not values:
        return []
    headers = [h.strip() for h in values[0]]
    return [dict(zip(headers, raw)) for raw in values[1:]]


def download_image(drive_service, folder_id, filename, dest_dir):
    query = f"'{folder_id}' in parents and name = '{filename}' and trashed = false"
    resp = drive_service.files().list(q=query, fields="files(id, name)").execute()
    files = resp.get("files", [])
    if not files:
        print(f"WARNING: image '{filename}' not found in Drive folder — leaving as-is", file=sys.stderr)
        return
    file_id = files[0]["id"]
    request = drive_service.files().get_media(fileId=file_id)
    dest_dir.mkdir(exist_ok=True)
    buf = io.BytesIO()
    downloader = MediaIoBaseDownload(buf, request)
    done = False
    while not done:
        _, done = downloader.next_chunk()
    (dest_dir / filename).write_bytes(buf.getvalue())


def render_product_card(row):
    name = html.escape(row.get("name", "").strip())
    desc = html.escape(row.get("description", "").strip())

    price_raw = row.get("price", "0").strip()
    try:
        price_display = f"{float(price_raw):.2f}"
    except ValueError:
        price_display = html.escape(price_raw)

    try:
        stock = int(float(row.get("stock", "0").strip() or 0))
    except ValueError:
        stock = 0

    image_filename = row.get("image_filename", "").strip()
    payment_link = row.get("payment_link", "").strip()

    if image_filename:
        img_html = (
            f'<img src="images/{html.escape(image_filename)}" alt="{name}" '
            f'style="width:100%;height:100%;object-fit:contain;border-radius:12px;">'
        )
    else:
        img_html = "[ NO PHOTO SET ]"

    if not payment_link:
        tag = "Coming Soon"
        cta = '<span class="btn-primary" style="opacity:0.5;cursor:default;">Payment link not set</span>'
    elif stock > 0:
        tag = "In Stock"
        cta = (
            f'<a class="btn-primary" href="{html.escape(payment_link)}" '
            f'target="_blank" rel="noopener">Buy now — card accepted</a>'
        )
    else:
        tag = "Sold Out"
        cta = '<span class="btn-primary" style="opacity:0.5;cursor:default;">Sold out</span>'

    return f"""      <div class="product-card">
        <div class="product-image">{img_html}</div>
        <div class="product-info">
          <span class="tag">{tag}</span>
          <h3>{name}</h3>
          <div class="product-price">${price_display}</div>
          <p class="product-desc">{desc}</p>
          {cta}
        </div>
      </div>"""


def render_products_block(rows_by_category):
    ordered_categories = CATEGORY_ORDER + sorted(
        c for c in rows_by_category if c not in CATEGORY_ORDER
    )
    parts = []
    for category in ordered_categories:
        rows = rows_by_category.get(category)
        if not rows:
            continue
        cards = "\n".join(render_product_card(r) for r in rows)
        parts.append(
            f'    <div class="category-group">\n'
            f'      <h3 class="category-title">{html.escape(category)}</h3>\n'
            f"{cards}\n"
            f"    </div>"
        )
    return "\n".join(parts)


def main():
    creds = get_credentials()
    sheets_service = build("sheets", "v4", credentials=creds, cache_discovery=False)
    drive_service = build("drive", "v3", credentials=creds, cache_discovery=False)

    sheet_id = os.environ["SHEET_ID"]
    folder_id = os.environ["DRIVE_FOLDER_ID"]

    rows = fetch_rows(sheets_service, sheet_id)
    active_rows = [r for r in rows if r.get("active", "").strip().upper() == "TRUE"]

    if not active_rows:
        print("No active products found in the sheet — leaving index.html untouched.")
        return

    rows_by_category = {}
    for row in active_rows:
        category = row.get("category", "").strip() or "Uncategorized"
        rows_by_category.setdefault(category, []).append(row)
        image_filename = row.get("image_filename", "").strip()
        if image_filename:
            download_image(drive_service, folder_id, image_filename, IMAGES_DIR)

    products_html = render_products_block(rows_by_category)

    html_text = INDEX_HTML.read_text()
    if BEGIN_MARKER not in html_text or END_MARKER not in html_text:
        print("ERROR: product markers not found in index.html — aborting", file=sys.stderr)
        sys.exit(1)

    before, rest = html_text.split(BEGIN_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)
    new_html = before + BEGIN_MARKER + "\n" + products_html + "\n    " + END_MARKER + after

    INDEX_HTML.write_text(new_html)
    print(f"Wrote {len(active_rows)} product(s) across {len(rows_by_category)} categor(y/ies) to index.html")


if __name__ == "__main__":
    main()
