#!/usr/bin/env python3
"""
Regenerates the product grid in shop.html, the Featured strip in index.html,
plus the machine-readable product data files, from the "Poke Liberty Product
Inventory" Google Sheet and "Poke Liberty Product Images" Drive folder.

Outputs:
  - shop.html                                  (full product grid between markers)
  - index.html                                 (Featured strip between markers)
  - images/<image_filename>                    (downloaded product photos)
  - data/products.json                         (fetched client-side by cart.html,
                                                 shop.html, and product.html)
  - netlify/functions/products-data.json       (bundled into the Checkout /
                                                 shipping-estimate / order-details
                                                 functions — same content,
                                                 co-located so they can `require` it)

Run automatically by .github/workflows/sync-inventory.yml on a schedule, or
manually:

    export GOOGLE_SERVICE_ACCOUNT_KEY="$(cat service-account.json)"
    export SHEET_ID=...
    export DRIVE_FOLDER_ID=...
    python3 scripts/build_products.py

Sheet columns expected (header row): id, category, name, description, price,
stock, image_filename, active, shipping_tier, condition, featured
(a legacy "payment_link" column may still exist in the sheet from an earlier
version of this pipeline — it's no longer used now that checkout goes
through the cart, and can be left or removed either way.)

shipping_tier must be "small", "medium", or "large" (see shipping-spec.md /
netlify/functions/shipping.js for the rate table) — rows missing it, or with
an unrecognized value, default to "medium" and print a warning, since
silently under-charging shipping on a "large" item is worse than a wrong
middle guess. Fill this in for every real product before going live.

condition is optional free text (e.g. "Near Mint", "Lightly Played") meant
for singles/graded pulls — leave it blank for sealed product and it simply
won't render a condition badge.

featured is optional TRUE/FALSE. Checked rows appear in index.html's
Featured strip (in Sheet order, capped at MAX_FEATURED). If nothing is
flagged, the strip falls back to the first in-stock active products instead
of shipping an empty homepage.
"""
import html
import io
import json
import os
import sys
from pathlib import Path
from urllib.parse import quote

from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload

REPO_ROOT = Path(__file__).resolve().parent.parent
SHOP_HTML = REPO_ROOT / "shop.html"
INDEX_HTML = REPO_ROOT / "index.html"
IMAGES_DIR = REPO_ROOT / "images"
DATA_JSON = REPO_ROOT / "data" / "products.json"
FUNCTION_DATA_JSON = REPO_ROOT / "netlify" / "functions" / "products-data.json"

GRID_BEGIN_MARKER = "<!-- BEGIN PRODUCTS: generated by scripts/build_products.py — do not hand-edit between these markers -->"
GRID_END_MARKER = "<!-- END PRODUCTS -->"
FEATURED_BEGIN_MARKER = "<!-- BEGIN FEATURED: generated by scripts/build_products.py — do not hand-edit between these markers -->"
FEATURED_END_MARKER = "<!-- END FEATURED -->"

MAX_FEATURED = 3

# Categories render in this order; anything else found in the sheet is
# appended alphabetically after these.
CATEGORY_ORDER = ["Sealed Product", "Singles for Collection", "Singles"]
# Case-insensitive lookup so a typo'd casing in the sheet (e.g. "raw cards
# for grading") still joins the right section instead of splintering off
# into its own group — maps lowercased name -> canonical display name.
CATEGORY_LOOKUP = {c.lower(): c for c in CATEGORY_ORDER}
VALID_SHIPPING_TIERS = {"small", "medium", "large"}

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets.readonly",
    "https://www.googleapis.com/auth/drive.readonly",
]


def get_credentials():
    key_json = os.environ["GOOGLE_SERVICE_ACCOUNT_KEY"]
    info = json.loads(key_json)
    return service_account.Credentials.from_service_account_info(info, scopes=SCOPES)


def fetch_rows(sheets_service, sheet_id):
    result = sheets_service.spreadsheets().values().get(
        spreadsheetId=sheet_id, range="A:Z"
    ).execute()
    values = result.get("values", [])
    if not values:
        return []
    headers = [h.strip() for h in values[0]]
    return [dict(zip(headers, raw)) for raw in values[1:]]


def download_image(drive_service, folder_id, filename, dest_dir):
    query = f"'{folder_id}' in parents and name = '{filename}' and trashed = false"
    resp = drive_service.files().list(q=query, fields="files(id, name)").execute()
    files = resp.get("files", [])
    if not files:
        print(f"WARNING: image '{filename}' not found in Drive folder — leaving as-is", file=sys.stderr)
        return
    file_id = files[0]["id"]
    request = drive_service.files().get_media(fileId=file_id)
    dest_dir.mkdir(exist_ok=True)
    buf = io.BytesIO()
    downloader = MediaIoBaseDownload(buf, request)
    done = False
    while not done:
        _, done = downloader.next_chunk()
    (dest_dir / filename).write_bytes(buf.getvalue())


def parse_product(row):
    """Normalizes one sheet row into the shape shared by products.json and
    the HTML renderers. Returns None for rows missing required fields."""
    product_id = row.get("id", "").strip()
    if not product_id:
        return None

    # Strip a leading currency symbol and thousands separators defensively
    # ("$180", "1,200.00") — a bare "180" still parses the same either way.
    price_raw = row.get("price", "0").strip().lstrip("$").replace(",", "")
    try:
        unit_amount = round(float(price_raw) * 100)
    except ValueError:
        unit_amount = 0
    if unit_amount == 0 and price_raw not in ("0", "0.0", "0.00", ""):
        print(f"WARNING: product '{product_id}' has an unparseable price "
              f"'{row.get('price', '')}' — it will show as $0.00", file=sys.stderr)

    try:
        stock = int(float(row.get("stock", "0").strip() or 0))
    except ValueError:
        stock = 0

    shipping_tier = row.get("shipping_tier", "").strip().lower()
    if shipping_tier not in VALID_SHIPPING_TIERS:
        if shipping_tier:
            print(f"WARNING: product '{product_id}' has unrecognized shipping_tier "
                  f"'{shipping_tier}' — defaulting to 'medium'", file=sys.stderr)
        else:
            print(f"WARNING: product '{product_id}' has no shipping_tier set — "
                  f"defaulting to 'medium'", file=sys.stderr)
        shipping_tier = "medium"

    category_raw = row.get("category", "").strip() or "Uncategorized"
    category = CATEGORY_LOOKUP.get(category_raw.lower(), category_raw)

    return {
        "id": product_id,
        "category": category,
        "name": row.get("name", "").strip(),
        "description": row.get("description", "").strip(),
        "unit_amount": unit_amount,
        "stock": max(stock, 0),
        "image_filename": row.get("image_filename", "").strip(),
        "active": row.get("active", "").strip().upper() == "TRUE",
        "shipping_tier": shipping_tier,
        "condition": row.get("condition", "").strip(),
        "featured": row.get("featured", "").strip().upper() == "TRUE",
    }


def stock_tag(stock):
    """(badge text, badge modifier class) for a product's current stock —
    used identically by the grid card, the featured card, and product.html
    so "low stock" urgency reads the same everywhere."""
    if stock <= 0:
        return "Sold Out", "sold-out"
    if stock <= 2:
        return f"Only {stock} left!", "low-stock"
    return "In Stock", ""


def render_product_card(product):
    name = html.escape(product["name"])
    desc = html.escape(product["description"])
    price_display = f"{product['unit_amount'] / 100:.2f}"
    stock = product["stock"]
    pid = html.escape(product["id"])
    detail_href = f"product.html?id={quote(product['id'])}"

    if product["image_filename"]:
        img_html = (
            f'<img src="images/{html.escape(product["image_filename"])}" alt="{name}" '
            f'style="width:100%;height:100%;object-fit:contain;border-radius:12px;">'
        )
    else:
        img_html = "[ NO PHOTO SET ]"

    tag_text, tag_class = stock_tag(stock)
    tag_class_attr = f" {tag_class}" if tag_class else ""
    condition_html = (
        f'<span class="condition-badge">{html.escape(product["condition"])}</span>'
        if product["condition"] else ""
    )

    if stock > 0:
        buy_row = f"""          <div class="buy-row">
            <div class="qty-stepper" data-qty-stepper>
              <button type="button" data-qty-decrement aria-label="Decrease quantity">–</button>
              <input type="number" value="1" min="1" max="{stock}" data-qty-input aria-label="Quantity">
              <button type="button" data-qty-increment aria-label="Increase quantity">+</button>
            </div>
            <button class="btn-primary" type="button" data-add-to-cart data-product-id="{pid}" data-max-stock="{stock}">Add to cart</button>
          </div>
          <p class="stock-note">{stock} in stock</p>"""
    else:
        buy_row = '          <button class="btn-primary" type="button" disabled aria-disabled="true">Sold out</button>'

    in_stock = "true" if stock > 0 else "false"
    search_name = html.escape(product["name"].strip().lower())

    return f"""      <div class="product-card" data-product-id="{pid}" data-in-stock="{in_stock}" data-price="{product['unit_amount']}" data-search-name="{search_name}">
        <a class="product-image" href="{detail_href}">{img_html}</a>
        <div class="product-info">
          <span class="tag{tag_class_attr}">{tag_text}</span>
          {condition_html}
          <h3><a href="{detail_href}">{name}</a></h3>
          <div class="product-price">${price_display}</div>
          <p class="product-desc">{desc}</p>
{buy_row}
        </div>
      </div>"""


def render_featured_card(product):
    name = html.escape(product["name"])
    price_display = f"{product['unit_amount'] / 100:.2f}"
    detail_href = f"product.html?id={quote(product['id'])}"

    if product["image_filename"]:
        img_html = (
            f'<img src="images/{html.escape(product["image_filename"])}" alt="{name}" '
            f'style="width:100%;height:100%;object-fit:contain;border-radius:10px;">'
        )
    else:
        img_html = "[ NO PHOTO SET ]"

    tag_text, tag_class = stock_tag(product["stock"])
    tag_class_attr = f" {tag_class}" if tag_class else ""

    return f"""    <div class="featured-card">
      <a class="featured-image" href="{detail_href}">{img_html}</a>
      <div class="featured-info">
        <span class="tag{tag_class_attr}">{tag_text}</span>
        <h3><a href="{detail_href}">{name}</a></h3>
        <div class="product-price">${price_display}</div>
        <a class="btn-secondary" href="{detail_href}">View &amp; buy</a>
      </div>
    </div>"""


def render_products_block(products_by_category):
    ordered_categories = CATEGORY_ORDER + sorted(
        c for c in products_by_category if c not in CATEGORY_ORDER
    )
    parts = []
    for category in ordered_categories:
        products = products_by_category.get(category)
        if not products:
            continue
        cards = "\n".join(render_product_card(p) for p in products)
        parts.append(
            f'    <div class="category-group" data-category="{html.escape(category)}">\n'
            f'      <h3 class="category-title">{html.escape(category)}</h3>\n'
            f"{cards}\n"
            f"    </div>"
        )
    return "\n".join(parts)


def pick_featured(active_products):
    flagged = [p for p in active_products if p["featured"]]
    if flagged:
        return flagged[:MAX_FEATURED]
    # Nothing manually flagged — fall back to the first in-stock items
    # rather than shipping an empty homepage; if nothing's in stock either,
    # fall back further to just the first active products.
    in_stock = [p for p in active_products if p["stock"] > 0]
    return (in_stock or active_products)[:MAX_FEATURED]


def replace_between_markers(html_text, begin_marker, end_marker, inner_html, source_label):
    if begin_marker not in html_text or end_marker not in html_text:
        print(f"ERROR: markers not found in {source_label} — aborting", file=sys.stderr)
        sys.exit(1)
    before, rest = html_text.split(begin_marker, 1)
    _, after = rest.split(end_marker, 1)
    return before + begin_marker + "\n" + inner_html + "\n    " + end_marker + after


def main():
    creds = get_credentials()
    sheets_service = build("sheets", "v4", credentials=creds, cache_discovery=False)
    drive_service = build("drive", "v3", credentials=creds, cache_discovery=False)

    sheet_id = os.environ["SHEET_ID"]
    folder_id = os.environ["DRIVE_FOLDER_ID"]

    rows = fetch_rows(sheets_service, sheet_id)
    all_products = [p for p in (parse_product(r) for r in rows) if p is not None]
    active_products = [p for p in all_products if p["active"]]

    # products.json includes every active product (in *and* out of stock) so
    # the cart page can still show "sold out" / re-validate correctly for
    # anything already sitting in someone's browser cart.
    products_by_id = {p["id"]: p for p in active_products}
    DATA_JSON.parent.mkdir(exist_ok=True)
    FUNCTION_DATA_JSON.parent.mkdir(parents=True, exist_ok=True)
    products_json_text = json.dumps(products_by_id, indent=2)
    DATA_JSON.write_text(products_json_text)
    FUNCTION_DATA_JSON.write_text(products_json_text)

    for product in active_products:
        if product["image_filename"]:
            download_image(drive_service, folder_id, product["image_filename"], IMAGES_DIR)

    if not active_products:
        print("No active products found in the sheet — shop.html/index.html left untouched, products.json cleared.")
        return

    products_by_category = {}
    for product in active_products:
        products_by_category.setdefault(product["category"], []).append(product)

    products_html = render_products_block(products_by_category)
    shop_html_text = SHOP_HTML.read_text()
    shop_html_text = replace_between_markers(
        shop_html_text, GRID_BEGIN_MARKER, GRID_END_MARKER, products_html, "shop.html"
    )
    SHOP_HTML.write_text(shop_html_text)

    featured_products = pick_featured(active_products)
    featured_html = "\n".join(render_featured_card(p) for p in featured_products)
    index_html_text = INDEX_HTML.read_text()
    index_html_text = replace_between_markers(
        index_html_text, FEATURED_BEGIN_MARKER, FEATURED_END_MARKER, featured_html, "index.html"
    )
    INDEX_HTML.write_text(index_html_text)

    print(
        f"Wrote {len(active_products)} product(s) across {len(products_by_category)} "
        f"categor(y/ies) to shop.html, {len(featured_products)} featured to index.html, "
        f"and products.json"
    )


if __name__ == "__main__":
    main()
